AWSTemplateFormatVersion: "2010-09-09"
Resources:
  chaliceDemo:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:  {{ table_name }} 
      AttributeDefinitions:
        - AttributeName: {{ table_primary_key }}
          AttributeType: "S"
      KeySchema:
        - AttributeName: {{ table_primary_key }}
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "10"
        WriteCapacityUnits: "10"

Outputs:
  TableName:
    Value: !Ref {{ table_name }}
    Description: Name of the newly created DynamoDB table